export const OBTENER_COMERCIOS = "OBTENER_COMERCIOS";
export const OBTENER_COMERCIOS_EXITO = "OBTENER_COMERCIOS_EXITO";
export const OBTENER_COMERCIOS_ERROR = "OBTENER_COMERCIOS_ERROR";

//obtener un solo comercio por su id
export const OBTENER_DETALLE_COMERCIO = "OBTENER_COMERCIO";
export const OBTENER_DETALLE_COMERCIO_EXITO = "OBTENER_COMERCIO_EXITO";
export const OBTENER_DETALLE_COMERCIO_ERROR = "OBTENER_COMERCIO_ERROR";
